
- name: Add hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update system
  yum:
    name: '*'
    state: latest

- name: Disable selinux
  shell: setenforce 0

- name: Disable selinux
  lineinfile:
    dest: /etc/selinux/config
    state: present
    regexp: '^SELINUX=enforcing'
    line: 'SELINUX=disabled'

